-- =============================================================================
-- Snowflake Procedure: Refresh Reporting Materialized Views / Aggregations
-- Called by Airflow reporting_aggregation DAG (daily)
-- =============================================================================

CREATE OR REPLACE PROCEDURE REPORTING.REFRESH_DAILY_SUMMARY(SUMMARY_DATE DATE)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    -- Upsert daily fraud summary
    MERGE INTO REPORTING.DAILY_FRAUD_SUMMARY tgt
    USING (
        SELECT
            :SUMMARY_DATE AS SUMMARY_DATE,
            COUNT(*) AS TOTAL_TRANSACTIONS,
            SUM(ft.TRANSACTION_AMOUNT) AS TOTAL_AMOUNT,
            SUM(CASE WHEN ft.IS_FRAUD THEN 1 ELSE 0 END) AS FRAUD_TRANSACTIONS,
            SUM(CASE WHEN ft.IS_FRAUD THEN ft.TRANSACTION_AMOUNT ELSE 0 END) AS FRAUD_AMOUNT,
            CASE WHEN COUNT(*) > 0
                THEN SUM(CASE WHEN ft.IS_FRAUD THEN 1 ELSE 0 END)::FLOAT / COUNT(*)
                ELSE 0 END AS FRAUD_RATE,
            AVG(ft.RISK_SCORE) AS AVG_RISK_SCORE,
            MEDIAN(ft.RISK_SCORE) AS MEDIAN_RISK_SCORE,
            SUM(CASE WHEN ft.RISK_SCORE >= 0.8 THEN 1 ELSE 0 END) AS HIGH_RISK_COUNT,
            SUM(CASE WHEN ft.RISK_SCORE >= 0.95 THEN 1 ELSE 0 END) AS CRITICAL_RISK_COUNT,
            COUNT(DISTINCT CASE WHEN ft.IS_FLAGGED THEN ft.TRANSACTION_ID END) AS ALERTS_GENERATED,
            0 AS ALERTS_RESOLVED,
            0 AS FALSE_POSITIVE_COUNT,
            0 AS FALSE_POSITIVE_RATE,
            0 AS AVG_RESOLUTION_TIME_MINUTES,
            COUNT(DISTINCT CASE WHEN ft.IS_FLAGGED THEN ft.CUSTOMER_KEY END) AS UNIQUE_ACCOUNTS_FLAGGED
        FROM ANALYTICS.FACT_TRANSACTIONS ft
        WHERE ft.DATE_KEY = TO_NUMBER(TO_CHAR(:SUMMARY_DATE, 'YYYYMMDD'))
    ) src
    ON tgt.SUMMARY_DATE = src.SUMMARY_DATE
    WHEN MATCHED THEN UPDATE SET
        tgt.TOTAL_TRANSACTIONS = src.TOTAL_TRANSACTIONS,
        tgt.TOTAL_AMOUNT = src.TOTAL_AMOUNT,
        tgt.FRAUD_TRANSACTIONS = src.FRAUD_TRANSACTIONS,
        tgt.FRAUD_AMOUNT = src.FRAUD_AMOUNT,
        tgt.FRAUD_RATE = src.FRAUD_RATE,
        tgt.AVG_RISK_SCORE = src.AVG_RISK_SCORE,
        tgt.MEDIAN_RISK_SCORE = src.MEDIAN_RISK_SCORE,
        tgt.HIGH_RISK_COUNT = src.HIGH_RISK_COUNT,
        tgt.CRITICAL_RISK_COUNT = src.CRITICAL_RISK_COUNT,
        tgt.ALERTS_GENERATED = src.ALERTS_GENERATED,
        tgt.UNIQUE_ACCOUNTS_FLAGGED = src.UNIQUE_ACCOUNTS_FLAGGED,
        tgt.REFRESHED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        SUMMARY_DATE, TOTAL_TRANSACTIONS, TOTAL_AMOUNT, FRAUD_TRANSACTIONS,
        FRAUD_AMOUNT, FRAUD_RATE, AVG_RISK_SCORE, MEDIAN_RISK_SCORE,
        HIGH_RISK_COUNT, CRITICAL_RISK_COUNT, ALERTS_GENERATED,
        ALERTS_RESOLVED, FALSE_POSITIVE_COUNT, FALSE_POSITIVE_RATE,
        AVG_RESOLUTION_TIME_MINUTES, UNIQUE_ACCOUNTS_FLAGGED, REFRESHED_AT
    ) VALUES (
        src.SUMMARY_DATE, src.TOTAL_TRANSACTIONS, src.TOTAL_AMOUNT, src.FRAUD_TRANSACTIONS,
        src.FRAUD_AMOUNT, src.FRAUD_RATE, src.AVG_RISK_SCORE, src.MEDIAN_RISK_SCORE,
        src.HIGH_RISK_COUNT, src.CRITICAL_RISK_COUNT, src.ALERTS_GENERATED,
        src.ALERTS_RESOLVED, src.FALSE_POSITIVE_COUNT, src.FALSE_POSITIVE_RATE,
        src.AVG_RESOLUTION_TIME_MINUTES, src.UNIQUE_ACCOUNTS_FLAGGED, CURRENT_TIMESTAMP()
    );

    RETURN 'Daily fraud summary refreshed for ' || :SUMMARY_DATE;
END;
$$;

-- =============================================================================
-- Procedure: Refresh Geography Fraud Breakdown
-- =============================================================================

CREATE OR REPLACE PROCEDURE REPORTING.REFRESH_FRAUD_BY_GEOGRAPHY(SUMMARY_DATE DATE)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    DELETE FROM REPORTING.FRAUD_BY_GEOGRAPHY WHERE SUMMARY_DATE = :SUMMARY_DATE;

    INSERT INTO REPORTING.FRAUD_BY_GEOGRAPHY (
        SUMMARY_DATE, COUNTRY_CODE, COUNTRY_NAME,
        TOTAL_TRANSACTIONS, FRAUD_TRANSACTIONS, FRAUD_RATE,
        TOTAL_AMOUNT, FRAUD_AMOUNT, AVG_RISK_SCORE
    )
    SELECT
        :SUMMARY_DATE,
        g.COUNTRY_CODE,
        g.COUNTRY_NAME,
        COUNT(*) AS TOTAL_TRANSACTIONS,
        SUM(CASE WHEN ft.IS_FRAUD THEN 1 ELSE 0 END) AS FRAUD_TRANSACTIONS,
        CASE WHEN COUNT(*) > 0
            THEN SUM(CASE WHEN ft.IS_FRAUD THEN 1 ELSE 0 END)::FLOAT / COUNT(*)
            ELSE 0 END AS FRAUD_RATE,
        SUM(ft.TRANSACTION_AMOUNT) AS TOTAL_AMOUNT,
        SUM(CASE WHEN ft.IS_FRAUD THEN ft.TRANSACTION_AMOUNT ELSE 0 END) AS FRAUD_AMOUNT,
        AVG(ft.RISK_SCORE) AS AVG_RISK_SCORE
    FROM ANALYTICS.FACT_TRANSACTIONS ft
    JOIN ANALYTICS.DIM_GEOGRAPHY g ON ft.GEOGRAPHY_KEY = g.GEOGRAPHY_KEY
    WHERE ft.DATE_KEY = TO_NUMBER(TO_CHAR(:SUMMARY_DATE, 'YYYYMMDD'))
    GROUP BY g.COUNTRY_CODE, g.COUNTRY_NAME
    HAVING COUNT(*) > 0;

    LET rows_inserted := SQLROWCOUNT;

    RETURN 'Refreshed geography fraud data: ' || :rows_inserted || ' countries for ' || :SUMMARY_DATE;
END;
$$;

-- =============================================================================
-- Procedure: Refresh Model Performance Metrics
-- =============================================================================

CREATE OR REPLACE PROCEDURE REPORTING.REFRESH_MODEL_PERFORMANCE(SUMMARY_DATE DATE)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    DELETE FROM REPORTING.MODEL_PERFORMANCE_DAILY WHERE SUMMARY_DATE = :SUMMARY_DATE;

    INSERT INTO REPORTING.MODEL_PERFORMANCE_DAILY (
        SUMMARY_DATE, MODEL_NAME, MODEL_VERSION,
        PREDICTIONS_COUNT, AVG_SCORE, SCORE_STDDEV,
        AVG_LATENCY_MS, P95_LATENCY_MS
    )
    SELECT
        :SUMMARY_DATE,
        'ensemble_scorer' AS MODEL_NAME,
        rs.MODEL_VERSION,
        COUNT(*) AS PREDICTIONS_COUNT,
        AVG(rs.OVERALL_SCORE) AS AVG_SCORE,
        STDDEV(rs.OVERALL_SCORE) AS SCORE_STDDEV,
        AVG(rs.LATENCY_MS) AS AVG_LATENCY_MS,
        PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY rs.LATENCY_MS) AS P95_LATENCY_MS
    FROM STAGING.STG_RISK_SCORES rs
    WHERE rs.SCORING_TIMESTAMP::DATE = :SUMMARY_DATE
    GROUP BY rs.MODEL_VERSION;

    LET rows_inserted := SQLROWCOUNT;

    RETURN 'Refreshed model performance: ' || :rows_inserted || ' model versions for ' || :SUMMARY_DATE;
END;
$$;

-- =============================================================================
-- Master Refresh Procedure (calls all sub-procedures)
-- =============================================================================

CREATE OR REPLACE PROCEDURE REPORTING.REFRESH_ALL(SUMMARY_DATE DATE)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    CALL REPORTING.REFRESH_DAILY_SUMMARY(:SUMMARY_DATE);
    CALL REPORTING.REFRESH_FRAUD_BY_GEOGRAPHY(:SUMMARY_DATE);
    CALL REPORTING.REFRESH_MODEL_PERFORMANCE(:SUMMARY_DATE);

    RETURN 'All reporting tables refreshed for ' || :SUMMARY_DATE;
END;
$$;
