"""Model monitoring: drift detection, performance tracking, and data quality.

Provides:
- Prediction distribution tracking and statistical tests
- Feature drift detection (PSI, KS-test, KL-divergence)
- Performance degradation alerting
- Data quality checks on input features
- Configurable alert thresholds and notification hooks
"""

from __future__ import annotations

import logging
import threading
import time
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Callable

import numpy as np

logger = logging.getLogger(__name__)


class AlertSeverity(str, Enum):
    """Monitoring alert severity levels."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class DriftType(str, Enum):
    """Types of detected drift."""

    PREDICTION = "prediction_drift"
    FEATURE = "feature_drift"
    PERFORMANCE = "performance_degradation"
    DATA_QUALITY = "data_quality"


@dataclass
class MonitoringAlert:
    """Alert generated by model monitoring."""

    alert_id: str
    severity: AlertSeverity
    drift_type: DriftType
    message: str
    metric_name: str
    metric_value: float
    threshold: float
    model_version: str
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    details: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "alert_id": self.alert_id,
            "severity": self.severity.value,
            "drift_type": self.drift_type.value,
            "message": self.message,
            "metric_name": self.metric_name,
            "metric_value": self.metric_value,
            "threshold": self.threshold,
            "model_version": self.model_version,
            "timestamp": self.timestamp,
            "details": self.details,
        }


@dataclass
class FeatureDriftResult:
    """Result of drift detection for a single feature."""

    feature_name: str
    drift_score: float
    is_drifted: bool
    test_method: str
    p_value: float | None = None
    threshold: float = 0.0
    details: dict[str, Any] = field(default_factory=dict)


@dataclass
class DataQualityReport:
    """Report of data quality checks on input features."""

    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    total_features: int = 0
    missing_count: int = 0
    out_of_range_count: int = 0
    type_mismatch_count: int = 0
    issues: list[dict[str, Any]] = field(default_factory=list)

    @property
    def is_healthy(self) -> bool:
        return self.missing_count == 0 and self.out_of_range_count == 0 and self.type_mismatch_count == 0

    @property
    def quality_score(self) -> float:
        if self.total_features == 0:
            return 1.0
        issues_total = self.missing_count + self.out_of_range_count + self.type_mismatch_count
        return max(0.0, 1.0 - (issues_total / self.total_features))


class PredictionDistributionTracker:
    """Tracks prediction score distributions over time windows.

    Maintains a sliding window of prediction scores and computes
    statistics for drift detection against a baseline.
    """

    def __init__(self, window_size: int = 10000, n_bins: int = 50) -> None:
        self._window_size = window_size
        self._n_bins = n_bins
        self._scores: deque[float] = deque(maxlen=window_size)
        self._baseline_histogram: np.ndarray | None = None
        self._baseline_edges: np.ndarray | None = None
        self._lock = threading.Lock()

    @property
    def count(self) -> int:
        return len(self._scores)

    def record(self, score: float) -> None:
        """Record a single prediction score."""
        with self._lock:
            self._scores.append(score)

    def record_batch(self, scores: np.ndarray | list[float]) -> None:
        """Record a batch of prediction scores."""
        with self._lock:
            self._scores.extend(scores)

    def set_baseline(self, scores: np.ndarray | list[float] | None = None) -> None:
        """Set baseline distribution from provided scores or current window."""
        with self._lock:
            if scores is not None:
                data = np.asarray(scores)
            elif len(self._scores) > 0:
                data = np.array(self._scores)
            else:
                return
            self._baseline_histogram, self._baseline_edges = np.histogram(
                data, bins=self._n_bins, range=(0.0, 1.0), density=True
            )

    def get_current_stats(self) -> dict[str, float]:
        """Get current distribution statistics."""
        with self._lock:
            if not self._scores:
                return {"count": 0, "mean": 0.0, "std": 0.0, "median": 0.0}
            arr = np.array(self._scores)
            return {
                "count": len(arr),
                "mean": float(np.mean(arr)),
                "std": float(np.std(arr)),
                "median": float(np.median(arr)),
                "p5": float(np.percentile(arr, 5)),
                "p25": float(np.percentile(arr, 25)),
                "p75": float(np.percentile(arr, 75)),
                "p95": float(np.percentile(arr, 95)),
                "min": float(np.min(arr)),
                "max": float(np.max(arr)),
            }

    def compute_psi(self) -> float | None:
        """Compute Population Stability Index between baseline and current.

        PSI < 0.1: no significant change
        PSI 0.1-0.25: moderate change
        PSI > 0.25: significant change

        Returns:
            PSI value, or None if baseline not set or insufficient data.
        """
        with self._lock:
            if self._baseline_histogram is None or len(self._scores) < 100:
                return None

            current_hist, _ = np.histogram(
                np.array(self._scores), bins=self._baseline_edges, density=True
            )

            # Add small epsilon to avoid division by zero
            eps = 1e-8
            baseline = self._baseline_histogram + eps
            current = current_hist + eps

            # Normalize
            baseline = baseline / baseline.sum()
            current = current / current.sum()

            psi = np.sum((current - baseline) * np.log(current / baseline))
            return float(psi)


class FeatureDriftDetector:
    """Detects drift in input feature distributions.

    Supports multiple detection methods:
    - PSI (Population Stability Index)
    - KS-test (Kolmogorov-Smirnov)
    - Mean/std shift detection
    """

    def __init__(
        self,
        feature_names: list[str],
        window_size: int = 5000,
        psi_threshold: float = 0.25,
        ks_threshold: float = 0.05,
    ) -> None:
        self._feature_names = feature_names
        self._window_size = window_size
        self._psi_threshold = psi_threshold
        self._ks_threshold = ks_threshold

        # Per-feature tracking
        self._feature_windows: dict[str, deque] = {
            name: deque(maxlen=window_size) for name in feature_names
        }
        self._baselines: dict[str, np.ndarray] = {}
        self._lock = threading.Lock()

    def set_baseline(self, feature_data: dict[str, np.ndarray]) -> None:
        """Set baseline distributions for all features.

        Args:
            feature_data: Dictionary mapping feature name to array of baseline values.
        """
        with self._lock:
            for name, values in feature_data.items():
                if name in self._feature_names:
                    self._baselines[name] = np.asarray(values)

    def record(self, features: dict[str, float]) -> None:
        """Record a single observation of feature values."""
        with self._lock:
            for name, value in features.items():
                if name in self._feature_windows:
                    self._feature_windows[name].append(value)

    def record_batch(self, feature_matrix: np.ndarray) -> None:
        """Record a batch of feature observations.

        Args:
            feature_matrix: Array of shape (n_samples, n_features).
        """
        with self._lock:
            for i, name in enumerate(self._feature_names):
                if i < feature_matrix.shape[1]:
                    self._feature_windows[name].extend(feature_matrix[:, i])

    def detect_drift(self, method: str = "psi") -> list[FeatureDriftResult]:
        """Run drift detection across all features.

        Args:
            method: Detection method ('psi', 'ks', or 'mean_shift').

        Returns:
            List of FeatureDriftResult for each feature.
        """
        results: list[FeatureDriftResult] = []

        with self._lock:
            for name in self._feature_names:
                if name not in self._baselines:
                    continue
                current_data = np.array(self._feature_windows[name])
                if len(current_data) < 100:
                    continue

                baseline_data = self._baselines[name]

                if method == "psi":
                    result = self._compute_feature_psi(name, baseline_data, current_data)
                elif method == "ks":
                    result = self._compute_ks_test(name, baseline_data, current_data)
                else:
                    result = self._compute_mean_shift(name, baseline_data, current_data)

                results.append(result)

        return results

    def get_drifted_features(self, method: str = "psi") -> list[FeatureDriftResult]:
        """Get only features that have drifted beyond threshold."""
        all_results = self.detect_drift(method=method)
        return [r for r in all_results if r.is_drifted]

    def _compute_feature_psi(
        self, name: str, baseline: np.ndarray, current: np.ndarray
    ) -> FeatureDriftResult:
        """Compute PSI for a single feature."""
        n_bins = 20
        eps = 1e-8

        # Determine bin edges from baseline
        edges = np.histogram_bin_edges(baseline, bins=n_bins)

        baseline_hist, _ = np.histogram(baseline, bins=edges, density=True)
        current_hist, _ = np.histogram(current, bins=edges, density=True)

        baseline_hist = baseline_hist + eps
        current_hist = current_hist + eps

        baseline_hist = baseline_hist / baseline_hist.sum()
        current_hist = current_hist / current_hist.sum()

        psi = float(np.sum((current_hist - baseline_hist) * np.log(current_hist / baseline_hist)))

        return FeatureDriftResult(
            feature_name=name,
            drift_score=psi,
            is_drifted=psi > self._psi_threshold,
            test_method="psi",
            threshold=self._psi_threshold,
            details={"psi_value": psi, "n_baseline": len(baseline), "n_current": len(current)},
        )

    def _compute_ks_test(
        self, name: str, baseline: np.ndarray, current: np.ndarray
    ) -> FeatureDriftResult:
        """Compute Kolmogorov-Smirnov test for a single feature."""
        from scipy import stats

        statistic, p_value = stats.ks_2samp(baseline, current)

        return FeatureDriftResult(
            feature_name=name,
            drift_score=float(statistic),
            is_drifted=p_value < self._ks_threshold,
            test_method="ks",
            p_value=float(p_value),
            threshold=self._ks_threshold,
            details={
                "ks_statistic": float(statistic),
                "p_value": float(p_value),
                "n_baseline": len(baseline),
                "n_current": len(current),
            },
        )

    def _compute_mean_shift(
        self, name: str, baseline: np.ndarray, current: np.ndarray
    ) -> FeatureDriftResult:
        """Detect drift via mean/std shift relative to baseline."""
        baseline_mean = float(np.mean(baseline))
        baseline_std = float(np.std(baseline)) or 1e-8
        current_mean = float(np.mean(current))

        # Z-score of shift
        shift = abs(current_mean - baseline_mean) / baseline_std
        threshold = 3.0  # > 3 standard deviations

        return FeatureDriftResult(
            feature_name=name,
            drift_score=shift,
            is_drifted=shift > threshold,
            test_method="mean_shift",
            threshold=threshold,
            details={
                "baseline_mean": baseline_mean,
                "baseline_std": baseline_std,
                "current_mean": current_mean,
                "shift_z_score": shift,
            },
        )


class DataQualityChecker:
    """Validates input feature quality before model inference.

    Checks for:
    - Missing/null values
    - Out-of-range values
    - Type mismatches
    - Feature count validation
    """

    def __init__(
        self,
        feature_names: list[str],
        feature_ranges: dict[str, tuple[float, float]] | None = None,
        required_features: list[str] | None = None,
    ) -> None:
        self._feature_names = feature_names
        self._feature_ranges = feature_ranges or {}
        self._required_features = required_features or feature_names

    def check(self, features: dict[str, Any]) -> DataQualityReport:
        """Run quality checks on a single feature vector.

        Args:
            features: Dictionary mapping feature name to value.

        Returns:
            DataQualityReport with issues found.
        """
        report = DataQualityReport(total_features=len(self._feature_names))
        issues: list[dict[str, Any]] = []

        # Check for missing features
        for name in self._required_features:
            if name not in features or features[name] is None:
                report.missing_count += 1
                issues.append({
                    "type": "missing",
                    "feature": name,
                    "message": f"Required feature '{name}' is missing or null",
                })

        # Check ranges and types
        for name, value in features.items():
            if name not in self._feature_names:
                continue
            if value is None:
                continue

            # Type check
            if not isinstance(value, (int, float, np.integer, np.floating)):
                report.type_mismatch_count += 1
                issues.append({
                    "type": "type_mismatch",
                    "feature": name,
                    "expected": "numeric",
                    "got": type(value).__name__,
                })
                continue

            # Range check
            if name in self._feature_ranges:
                low, high = self._feature_ranges[name]
                if value < low or value > high:
                    report.out_of_range_count += 1
                    issues.append({
                        "type": "out_of_range",
                        "feature": name,
                        "value": float(value),
                        "expected_range": [low, high],
                    })

        report.issues = issues
        return report

    def check_batch(self, feature_matrix: np.ndarray) -> DataQualityReport:
        """Run quality checks on a batch of features.

        Args:
            feature_matrix: Array of shape (n_samples, n_features).

        Returns:
            Aggregated DataQualityReport.
        """
        report = DataQualityReport(total_features=len(self._feature_names))
        issues: list[dict[str, Any]] = []

        # Check for NaN values
        nan_mask = np.isnan(feature_matrix)
        nan_counts = nan_mask.sum(axis=0)

        for i, name in enumerate(self._feature_names):
            if i >= feature_matrix.shape[1]:
                report.missing_count += 1
                issues.append({
                    "type": "missing",
                    "feature": name,
                    "message": f"Feature column {i} missing from input matrix",
                })
                continue

            if nan_counts[i] > 0:
                report.missing_count += 1
                issues.append({
                    "type": "missing",
                    "feature": name,
                    "nan_count": int(nan_counts[i]),
                    "nan_fraction": float(nan_counts[i] / feature_matrix.shape[0]),
                })

            # Range check
            if name in self._feature_ranges:
                low, high = self._feature_ranges[name]
                col = feature_matrix[:, i]
                valid = col[~np.isnan(col)]
                if len(valid) > 0 and (valid.min() < low or valid.max() > high):
                    report.out_of_range_count += 1
                    issues.append({
                        "type": "out_of_range",
                        "feature": name,
                        "actual_min": float(valid.min()),
                        "actual_max": float(valid.max()),
                        "expected_range": [low, high],
                    })

        report.issues = issues
        return report


class ModelMonitor:
    """Comprehensive model monitoring with alerting.

    Combines prediction distribution tracking, feature drift detection,
    data quality checks, and performance monitoring into a single interface.
    Generates alerts when thresholds are breached.
    """

    def __init__(
        self,
        model_version: str,
        feature_names: list[str],
        prediction_window_size: int = 10000,
        feature_window_size: int = 5000,
        psi_threshold: float = 0.25,
        ks_threshold: float = 0.05,
        latency_threshold_ms: float = 100.0,
        error_rate_threshold: float = 0.05,
        feature_ranges: dict[str, tuple[float, float]] | None = None,
        alert_callback: Callable[[MonitoringAlert], None] | None = None,
    ) -> None:
        self._model_version = model_version
        self._feature_names = feature_names
        self._latency_threshold_ms = latency_threshold_ms
        self._error_rate_threshold = error_rate_threshold
        self._alert_callback = alert_callback

        # Sub-components
        self._prediction_tracker = PredictionDistributionTracker(
            window_size=prediction_window_size
        )
        self._drift_detector = FeatureDriftDetector(
            feature_names=feature_names,
            window_size=feature_window_size,
            psi_threshold=psi_threshold,
            ks_threshold=ks_threshold,
        )
        self._quality_checker = DataQualityChecker(
            feature_names=feature_names,
            feature_ranges=feature_ranges,
        )

        # Performance tracking
        self._latencies: deque[float] = deque(maxlen=prediction_window_size)
        self._error_window: deque[bool] = deque(maxlen=1000)
        self._alert_history: list[MonitoringAlert] = []
        self._alert_counter = 0
        self._lock = threading.Lock()

    @property
    def prediction_tracker(self) -> PredictionDistributionTracker:
        return self._prediction_tracker

    @property
    def drift_detector(self) -> FeatureDriftDetector:
        return self._drift_detector

    @property
    def quality_checker(self) -> DataQualityChecker:
        return self._quality_checker

    def set_baselines(
        self,
        prediction_scores: np.ndarray | list[float] | None = None,
        feature_data: dict[str, np.ndarray] | None = None,
    ) -> None:
        """Set baseline distributions for drift detection.

        Should be called with training or validation data distributions.

        Args:
            prediction_scores: Baseline prediction score distribution.
            feature_data: Baseline feature distributions per feature name.
        """
        if prediction_scores is not None:
            self._prediction_tracker.set_baseline(prediction_scores)
        if feature_data is not None:
            self._drift_detector.set_baseline(feature_data)

    def record_prediction(
        self,
        score: float,
        features: dict[str, float] | None = None,
        latency_ms: float = 0.0,
        is_error: bool = False,
    ) -> list[MonitoringAlert]:
        """Record a single prediction and check for issues.

        Args:
            score: Prediction score (0.0 to 1.0).
            features: Input feature values (optional, for drift tracking).
            latency_ms: Prediction latency in milliseconds.
            is_error: Whether this prediction resulted in an error.

        Returns:
            List of any alerts triggered by this observation.
        """
        alerts: list[MonitoringAlert] = []

        self._prediction_tracker.record(score)

        if features:
            self._drift_detector.record(features)

        with self._lock:
            self._latencies.append(latency_ms)
            self._error_window.append(is_error)

        # Check latency threshold
        if latency_ms > self._latency_threshold_ms:
            alert = self._create_alert(
                severity=AlertSeverity.WARNING,
                drift_type=DriftType.PERFORMANCE,
                message=f"Prediction latency {latency_ms:.1f}ms exceeds threshold {self._latency_threshold_ms}ms",
                metric_name="prediction_latency_ms",
                metric_value=latency_ms,
                threshold=self._latency_threshold_ms,
            )
            alerts.append(alert)

        return alerts

    def record_batch(
        self,
        scores: np.ndarray,
        feature_matrix: np.ndarray | None = None,
        latency_ms: float = 0.0,
        errors: int = 0,
    ) -> list[MonitoringAlert]:
        """Record a batch of predictions.

        Args:
            scores: Array of prediction scores.
            feature_matrix: Feature matrix of shape (n_samples, n_features).
            latency_ms: Total batch latency.
            errors: Number of errors in this batch.

        Returns:
            List of alerts triggered.
        """
        alerts: list[MonitoringAlert] = []

        self._prediction_tracker.record_batch(scores)

        if feature_matrix is not None:
            self._drift_detector.record_batch(feature_matrix)

        with self._lock:
            per_sample_latency = latency_ms / len(scores) if len(scores) > 0 else 0
            for _ in range(len(scores)):
                self._latencies.append(per_sample_latency)
            for i in range(len(scores)):
                self._error_window.append(i < errors)

        return alerts

    def check_prediction_drift(self) -> MonitoringAlert | None:
        """Check if prediction score distribution has drifted from baseline.

        Returns:
            Alert if drift detected, None otherwise.
        """
        psi = self._prediction_tracker.compute_psi()
        if psi is None:
            return None

        if psi > 0.25:
            severity = AlertSeverity.CRITICAL
        elif psi > 0.1:
            severity = AlertSeverity.WARNING
        else:
            return None

        stats = self._prediction_tracker.get_current_stats()
        return self._create_alert(
            severity=severity,
            drift_type=DriftType.PREDICTION,
            message=f"Prediction distribution drift detected (PSI={psi:.4f})",
            metric_name="prediction_psi",
            metric_value=psi,
            threshold=0.1,
            details={"current_stats": stats},
        )

    def check_feature_drift(self, method: str = "psi") -> list[MonitoringAlert]:
        """Check all features for drift.

        Args:
            method: Detection method ('psi', 'ks', or 'mean_shift').

        Returns:
            List of alerts for drifted features.
        """
        drifted = self._drift_detector.get_drifted_features(method=method)
        alerts: list[MonitoringAlert] = []

        for result in drifted:
            severity = (
                AlertSeverity.CRITICAL if result.drift_score > 0.5
                else AlertSeverity.WARNING
            )
            alert = self._create_alert(
                severity=severity,
                drift_type=DriftType.FEATURE,
                message=(
                    f"Feature '{result.feature_name}' drift detected "
                    f"({result.test_method}={result.drift_score:.4f})"
                ),
                metric_name=f"feature_drift_{result.feature_name}",
                metric_value=result.drift_score,
                threshold=result.threshold,
                details=result.details,
            )
            alerts.append(alert)

        return alerts

    def check_performance(self) -> list[MonitoringAlert]:
        """Check for performance degradation (latency and error rate).

        Returns:
            List of performance alerts.
        """
        alerts: list[MonitoringAlert] = []

        with self._lock:
            latencies = list(self._latencies)
            errors = list(self._error_window)

        # Latency check (P95)
        if len(latencies) >= 100:
            p95_latency = float(np.percentile(latencies, 95))
            if p95_latency > self._latency_threshold_ms:
                alert = self._create_alert(
                    severity=AlertSeverity.WARNING,
                    drift_type=DriftType.PERFORMANCE,
                    message=f"P95 latency {p95_latency:.1f}ms exceeds threshold",
                    metric_name="p95_latency_ms",
                    metric_value=p95_latency,
                    threshold=self._latency_threshold_ms,
                    details={
                        "p50_latency": float(np.percentile(latencies, 50)),
                        "p99_latency": float(np.percentile(latencies, 99)),
                        "window_size": len(latencies),
                    },
                )
                alerts.append(alert)

        # Error rate check
        if len(errors) >= 100:
            error_rate = sum(errors) / len(errors)
            if error_rate > self._error_rate_threshold:
                alert = self._create_alert(
                    severity=AlertSeverity.CRITICAL,
                    drift_type=DriftType.PERFORMANCE,
                    message=f"Error rate {error_rate:.2%} exceeds threshold {self._error_rate_threshold:.2%}",
                    metric_name="error_rate",
                    metric_value=error_rate,
                    threshold=self._error_rate_threshold,
                    details={"total_errors": sum(errors), "window_size": len(errors)},
                )
                alerts.append(alert)

        return alerts

    def check_data_quality(self, features: dict[str, Any]) -> DataQualityReport:
        """Run data quality checks on input features.

        Args:
            features: Feature dictionary to validate.

        Returns:
            DataQualityReport with any issues found.
        """
        return self._quality_checker.check(features)

    def check_data_quality_batch(self, feature_matrix: np.ndarray) -> DataQualityReport:
        """Run data quality checks on a batch of features."""
        return self._quality_checker.check_batch(feature_matrix)

    def run_all_checks(self) -> list[MonitoringAlert]:
        """Run all monitoring checks and return any triggered alerts.

        Combines prediction drift, feature drift, and performance checks.

        Returns:
            List of all alerts triggered.
        """
        alerts: list[MonitoringAlert] = []

        # Prediction drift
        pred_alert = self.check_prediction_drift()
        if pred_alert:
            alerts.append(pred_alert)

        # Feature drift
        alerts.extend(self.check_feature_drift())

        # Performance
        alerts.extend(self.check_performance())

        # Notify callback for each alert
        if self._alert_callback:
            for alert in alerts:
                self._alert_callback(alert)

        return alerts

    def get_health_status(self) -> dict[str, Any]:
        """Get overall model health status.

        Returns:
            Dictionary with health metrics and status.
        """
        pred_stats = self._prediction_tracker.get_current_stats()
        psi = self._prediction_tracker.compute_psi()

        with self._lock:
            latencies = list(self._latencies)
            errors = list(self._error_window)

        error_rate = sum(errors) / len(errors) if errors else 0.0
        avg_latency = float(np.mean(latencies)) if latencies else 0.0

        # Determine overall health
        health = "healthy"
        if psi and psi > 0.25:
            health = "degraded"
        if error_rate > self._error_rate_threshold:
            health = "unhealthy"

        return {
            "status": health,
            "model_version": self._model_version,
            "prediction_stats": pred_stats,
            "prediction_psi": psi,
            "avg_latency_ms": round(avg_latency, 3),
            "p95_latency_ms": round(float(np.percentile(latencies, 95)), 3) if latencies else 0.0,
            "error_rate": round(error_rate, 4),
            "total_predictions": pred_stats.get("count", 0),
            "active_alerts": len([a for a in self._alert_history[-100:] if a.severity == AlertSeverity.CRITICAL]),
        }

    def get_alerts(self, limit: int = 50) -> list[dict[str, Any]]:
        """Get recent alerts."""
        return [a.to_dict() for a in self._alert_history[-limit:]]

    def _create_alert(
        self,
        severity: AlertSeverity,
        drift_type: DriftType,
        message: str,
        metric_name: str,
        metric_value: float,
        threshold: float,
        details: dict[str, Any] | None = None,
    ) -> MonitoringAlert:
        """Create and store an alert."""
        self._alert_counter += 1
        alert = MonitoringAlert(
            alert_id=f"MON-{self._alert_counter:06d}",
            severity=severity,
            drift_type=drift_type,
            message=message,
            metric_name=metric_name,
            metric_value=metric_value,
            threshold=threshold,
            model_version=self._model_version,
            details=details or {},
        )
        self._alert_history.append(alert)

        logger.warning(
            "Model monitoring alert: [%s] %s (metric=%s, value=%.4f, threshold=%.4f)",
            severity.value.upper(),
            message,
            metric_name,
            metric_value,
            threshold,
        )
        return alert
