CREATE SCHEMA IF NOT EXISTS SECURITY;

CREATE TABLE IF NOT EXISTS SECURITY.POWERBI_USER_TENANT_ACCESS (
    USER_PRINCIPAL_NAME VARCHAR(255) NOT NULL,
    TENANT_ID VARCHAR(128) NOT NULL,
    ACCESS_ROLE VARCHAR(64) NOT NULL DEFAULT 'viewer',
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (USER_PRINCIPAL_NAME, TENANT_ID)
);

CREATE OR REPLACE VIEW SECURITY.VW_POWERBI_USER_TENANT_ACCESS_ACTIVE AS
SELECT
    USER_PRINCIPAL_NAME,
    TENANT_ID,
    ACCESS_ROLE
FROM SECURITY.POWERBI_USER_TENANT_ACCESS
WHERE IS_ACTIVE = TRUE;

MERGE INTO SECURITY.POWERBI_USER_TENANT_ACCESS tgt
USING (
    SELECT 'admin@riskpulse.local' AS USER_PRINCIPAL_NAME, 'default' AS TENANT_ID, 'admin' AS ACCESS_ROLE
) src
ON tgt.USER_PRINCIPAL_NAME = src.USER_PRINCIPAL_NAME
   AND tgt.TENANT_ID = src.TENANT_ID
WHEN MATCHED THEN UPDATE SET
    ACCESS_ROLE = src.ACCESS_ROLE,
    IS_ACTIVE = TRUE,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    USER_PRINCIPAL_NAME,
    TENANT_ID,
    ACCESS_ROLE
) VALUES (
    src.USER_PRINCIPAL_NAME,
    src.TENANT_ID,
    src.ACCESS_ROLE
);
