-- =============================================================================
-- Snowflake ANALYTICS Schema
-- Star schema (fact + dimension tables) for analytical queries
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- =============================================================================
-- DIMENSION TABLES
-- =============================================================================

-- Date Dimension
CREATE TABLE IF NOT EXISTS ANALYTICS.DIM_DATE (
    DATE_KEY NUMBER PRIMARY KEY,
    FULL_DATE DATE NOT NULL,
    DAY_OF_WEEK NUMBER NOT NULL,
    DAY_NAME VARCHAR(10) NOT NULL,
    DAY_OF_MONTH NUMBER NOT NULL,
    DAY_OF_YEAR NUMBER NOT NULL,
    WEEK_OF_YEAR NUMBER NOT NULL,
    MONTH_NUMBER NUMBER NOT NULL,
    MONTH_NAME VARCHAR(10) NOT NULL,
    QUARTER NUMBER NOT NULL,
    YEAR NUMBER NOT NULL,
    IS_WEEKEND BOOLEAN NOT NULL,
    IS_HOLIDAY BOOLEAN DEFAULT FALSE,
    FISCAL_QUARTER NUMBER,
    FISCAL_YEAR NUMBER
);

-- Customer Dimension (SCD Type 2)
CREATE TABLE IF NOT EXISTS ANALYTICS.DIM_CUSTOMER (
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    RISK_TIER VARCHAR(20),
    ACCOUNT_AGE_DAYS NUMBER,
    TOTAL_LIFETIME_TRANSACTIONS NUMBER,
    AVG_TRANSACTION_AMOUNT NUMBER(15, 2),
    MAX_TRANSACTION_AMOUNT NUMBER(15, 2),
    PREFERRED_CHANNEL VARCHAR(20),
    PREFERRED_CARD_TYPE VARCHAR(20),
    EFFECTIVE_FROM TIMESTAMPTZ NOT NULL,
    EFFECTIVE_TO TIMESTAMPTZ DEFAULT '9999-12-31'::TIMESTAMPTZ,
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE ANALYTICS.DIM_CUSTOMER SET CLUSTER BY (CUSTOMER_ID, IS_CURRENT);

-- Merchant Dimension
CREATE TABLE IF NOT EXISTS ANALYTICS.DIM_MERCHANT (
    MERCHANT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    MERCHANT_ID VARCHAR(64) NOT NULL,
    MERCHANT_NAME VARCHAR(255),
    CATEGORY_CODE VARCHAR(10),
    CATEGORY_NAME VARCHAR(100),
    RISK_CATEGORY VARCHAR(20) DEFAULT 'standard',
    COUNTRY VARCHAR(3),
    TOTAL_TRANSACTIONS NUMBER DEFAULT 0,
    FRAUD_RATE NUMBER(7, 4) DEFAULT 0,
    LAST_UPDATED TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Geography Dimension
CREATE TABLE IF NOT EXISTS ANALYTICS.DIM_GEOGRAPHY (
    GEOGRAPHY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    COUNTRY_CODE VARCHAR(3) NOT NULL,
    COUNTRY_NAME VARCHAR(100) NOT NULL,
    CITY VARCHAR(100),
    REGION VARCHAR(100),
    CONTINENT VARCHAR(20),
    RISK_LEVEL VARCHAR(20) DEFAULT 'standard',
    IS_HIGH_RISK_COUNTRY BOOLEAN DEFAULT FALSE
);

-- Channel Dimension
CREATE TABLE IF NOT EXISTS ANALYTICS.DIM_CHANNEL (
    CHANNEL_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CHANNEL_CODE VARCHAR(20) NOT NULL,
    CHANNEL_NAME VARCHAR(50) NOT NULL,
    CHANNEL_DESCRIPTION VARCHAR(200),
    IS_DIGITAL BOOLEAN NOT NULL,
    RISK_WEIGHT NUMBER(3, 2) DEFAULT 1.0
);

-- Alert Type Dimension
CREATE TABLE IF NOT EXISTS ANALYTICS.DIM_ALERT_TYPE (
    ALERT_TYPE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    ALERT_TYPE_CODE VARCHAR(50) NOT NULL,
    ALERT_TYPE_NAME VARCHAR(100) NOT NULL,
    DETECTION_METHOD VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(500)
);

-- =============================================================================
-- FACT TABLES
-- =============================================================================

-- Transaction Fact Table
CREATE TABLE IF NOT EXISTS ANALYTICS.FACT_TRANSACTIONS (
    TRANSACTION_KEY NUMBER AUTOINCREMENT,
    TRANSACTION_ID VARCHAR(64) NOT NULL,
    DATE_KEY NUMBER REFERENCES ANALYTICS.DIM_DATE(DATE_KEY),
    CUSTOMER_KEY NUMBER REFERENCES ANALYTICS.DIM_CUSTOMER(CUSTOMER_KEY),
    MERCHANT_KEY NUMBER REFERENCES ANALYTICS.DIM_MERCHANT(MERCHANT_KEY),
    GEOGRAPHY_KEY NUMBER REFERENCES ANALYTICS.DIM_GEOGRAPHY(GEOGRAPHY_KEY),
    CHANNEL_KEY NUMBER REFERENCES ANALYTICS.DIM_CHANNEL(CHANNEL_KEY),
    TRANSACTION_AMOUNT NUMBER(15, 2) NOT NULL,
    TRANSACTION_CURRENCY VARCHAR(3) NOT NULL,
    RISK_SCORE NUMBER(5, 4),
    IS_FRAUD BOOLEAN DEFAULT FALSE,
    IS_FLAGGED BOOLEAN DEFAULT FALSE,
    ALERT_SEVERITY VARCHAR(20),
    PROCESSING_LATENCY_MS NUMBER,
    TRANSACTION_TIMESTAMP TIMESTAMPTZ NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE ANALYTICS.FACT_TRANSACTIONS SET CLUSTER BY (DATE_KEY, CUSTOMER_KEY);

-- Alert Fact Table
CREATE TABLE IF NOT EXISTS ANALYTICS.FACT_ALERTS (
    ALERT_KEY NUMBER AUTOINCREMENT,
    ALERT_ID VARCHAR(64) NOT NULL,
    TRANSACTION_KEY NUMBER,
    DATE_KEY NUMBER REFERENCES ANALYTICS.DIM_DATE(DATE_KEY),
    CUSTOMER_KEY NUMBER REFERENCES ANALYTICS.DIM_CUSTOMER(CUSTOMER_KEY),
    ALERT_TYPE_KEY NUMBER REFERENCES ANALYTICS.DIM_ALERT_TYPE(ALERT_TYPE_KEY),
    RISK_SCORE NUMBER(5, 4),
    SEVERITY VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    RESOLUTION_TIME_MINUTES NUMBER,
    IS_FALSE_POSITIVE BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    RESOLVED_AT TIMESTAMPTZ
);

-- =============================================================================
-- POPULATE DATE DIMENSION (2020-2030)
-- =============================================================================

-- Generate date dimension data
INSERT INTO ANALYTICS.DIM_DATE
SELECT
    TO_NUMBER(TO_CHAR(DATEADD(DAY, SEQ4(), '2020-01-01'::DATE), 'YYYYMMDD')) AS DATE_KEY,
    DATEADD(DAY, SEQ4(), '2020-01-01'::DATE) AS FULL_DATE,
    DAYOFWEEK(DATEADD(DAY, SEQ4(), '2020-01-01'::DATE)) AS DAY_OF_WEEK,
    DAYNAME(DATEADD(DAY, SEQ4(), '2020-01-01'::DATE)) AS DAY_NAME,
    DAY(DATEADD(DAY, SEQ4(), '2020-01-01'::DATE)) AS DAY_OF_MONTH,
    DAYOFYEAR(DATEADD(DAY, SEQ4(), '2020-01-01'::DATE)) AS DAY_OF_YEAR,
    WEEKOFYEAR(DATEADD(DAY, SEQ4(), '2020-01-01'::DATE)) AS WEEK_OF_YEAR,
    MONTH(DATEADD(DAY, SEQ4(), '2020-01-01'::DATE)) AS MONTH_NUMBER,
    MONTHNAME(DATEADD(DAY, SEQ4(), '2020-01-01'::DATE)) AS MONTH_NAME,
    QUARTER(DATEADD(DAY, SEQ4(), '2020-01-01'::DATE)) AS QUARTER,
    YEAR(DATEADD(DAY, SEQ4(), '2020-01-01'::DATE)) AS YEAR,
    CASE WHEN DAYOFWEEK(DATEADD(DAY, SEQ4(), '2020-01-01'::DATE)) IN (0, 6) THEN TRUE ELSE FALSE END AS IS_WEEKEND,
    FALSE AS IS_HOLIDAY,
    CEIL(MONTH(DATEADD(DAY, SEQ4(), '2020-01-01'::DATE)) / 3.0) AS FISCAL_QUARTER,
    YEAR(DATEADD(DAY, SEQ4(), '2020-01-01'::DATE)) AS FISCAL_YEAR
FROM TABLE(GENERATOR(ROWCOUNT => 4018))  -- ~11 years of dates
WHERE DATEADD(DAY, SEQ4(), '2020-01-01'::DATE) <= '2030-12-31'::DATE;

-- Populate Channel Dimension
INSERT INTO ANALYTICS.DIM_CHANNEL (CHANNEL_CODE, CHANNEL_NAME, CHANNEL_DESCRIPTION, IS_DIGITAL, RISK_WEIGHT)
VALUES
    ('online', 'Online', 'E-commerce and web-based transactions', TRUE, 1.2),
    ('pos', 'Point of Sale', 'In-store physical terminal transactions', FALSE, 0.8),
    ('atm', 'ATM', 'Automated teller machine withdrawals', FALSE, 1.0),
    ('mobile', 'Mobile', 'Mobile app and mobile payment transactions', TRUE, 1.1);

-- Populate Alert Type Dimension
INSERT INTO ANALYTICS.DIM_ALERT_TYPE (ALERT_TYPE_CODE, ALERT_TYPE_NAME, DETECTION_METHOD, DESCRIPTION)
VALUES
    ('rule_based', 'Rule-Based Alert', 'Rules Engine', 'Alert triggered by configurable business rules'),
    ('anomaly', 'Anomaly Detection Alert', 'Isolation Forest', 'Alert triggered by statistical anomaly detection'),
    ('ml_score', 'ML Score Alert', 'XGBoost/LightGBM', 'Alert triggered by ML risk scoring model'),
    ('ensemble', 'Ensemble Alert', 'Weighted Ensemble', 'Alert from combined scoring methods');
