-- =============================================================================
-- Snowflake REPORTING Schema
-- Pre-aggregated tables for dashboard performance
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS REPORTING;

-- Daily Fraud Summary (refreshed daily by Airflow DAG)
CREATE TABLE IF NOT EXISTS REPORTING.DAILY_FRAUD_SUMMARY (
    SUMMARY_DATE DATE NOT NULL,
    TOTAL_TRANSACTIONS NUMBER NOT NULL DEFAULT 0,
    TOTAL_AMOUNT NUMBER(18, 2) NOT NULL DEFAULT 0,
    FRAUD_TRANSACTIONS NUMBER NOT NULL DEFAULT 0,
    FRAUD_AMOUNT NUMBER(18, 2) NOT NULL DEFAULT 0,
    FRAUD_RATE NUMBER(7, 4) DEFAULT 0,
    AVG_RISK_SCORE NUMBER(5, 4) DEFAULT 0,
    MEDIAN_RISK_SCORE NUMBER(5, 4) DEFAULT 0,
    HIGH_RISK_COUNT NUMBER DEFAULT 0,
    CRITICAL_RISK_COUNT NUMBER DEFAULT 0,
    ALERTS_GENERATED NUMBER DEFAULT 0,
    ALERTS_RESOLVED NUMBER DEFAULT 0,
    FALSE_POSITIVE_COUNT NUMBER DEFAULT 0,
    FALSE_POSITIVE_RATE NUMBER(7, 4) DEFAULT 0,
    AVG_RESOLUTION_TIME_MINUTES NUMBER DEFAULT 0,
    UNIQUE_ACCOUNTS_FLAGGED NUMBER DEFAULT 0,
    REFRESHED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SUMMARY_DATE)
);

-- Hourly Transaction Metrics (for real-time-ish monitoring via Snowflake)
CREATE TABLE IF NOT EXISTS REPORTING.HOURLY_TRANSACTION_METRICS (
    METRIC_HOUR TIMESTAMPTZ NOT NULL,
    TOTAL_TRANSACTIONS NUMBER DEFAULT 0,
    TOTAL_AMOUNT NUMBER(18, 2) DEFAULT 0,
    AVG_AMOUNT NUMBER(15, 2) DEFAULT 0,
    MAX_AMOUNT NUMBER(15, 2) DEFAULT 0,
    FRAUD_COUNT NUMBER DEFAULT 0,
    HIGH_RISK_COUNT NUMBER DEFAULT 0,
    AVG_RISK_SCORE NUMBER(5, 4) DEFAULT 0,
    AVG_LATENCY_MS NUMBER DEFAULT 0,
    ERROR_COUNT NUMBER DEFAULT 0,
    CHANNEL_ONLINE_COUNT NUMBER DEFAULT 0,
    CHANNEL_POS_COUNT NUMBER DEFAULT 0,
    CHANNEL_ATM_COUNT NUMBER DEFAULT 0,
    CHANNEL_MOBILE_COUNT NUMBER DEFAULT 0,
    REFRESHED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (METRIC_HOUR)
);

-- Fraud by Geography (for map visualizations)
CREATE TABLE IF NOT EXISTS REPORTING.FRAUD_BY_GEOGRAPHY (
    SUMMARY_DATE DATE NOT NULL,
    COUNTRY_CODE VARCHAR(3) NOT NULL,
    COUNTRY_NAME VARCHAR(100),
    TOTAL_TRANSACTIONS NUMBER DEFAULT 0,
    FRAUD_TRANSACTIONS NUMBER DEFAULT 0,
    FRAUD_RATE NUMBER(7, 4) DEFAULT 0,
    TOTAL_AMOUNT NUMBER(18, 2) DEFAULT 0,
    FRAUD_AMOUNT NUMBER(18, 2) DEFAULT 0,
    AVG_RISK_SCORE NUMBER(5, 4) DEFAULT 0,
    REFRESHED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SUMMARY_DATE, COUNTRY_CODE)
);

-- Fraud by Merchant Category
CREATE TABLE IF NOT EXISTS REPORTING.FRAUD_BY_MERCHANT_CATEGORY (
    SUMMARY_DATE DATE NOT NULL,
    CATEGORY_CODE VARCHAR(10) NOT NULL,
    CATEGORY_NAME VARCHAR(100),
    TOTAL_TRANSACTIONS NUMBER DEFAULT 0,
    FRAUD_TRANSACTIONS NUMBER DEFAULT 0,
    FRAUD_RATE NUMBER(7, 4) DEFAULT 0,
    TOTAL_AMOUNT NUMBER(18, 2) DEFAULT 0,
    FRAUD_AMOUNT NUMBER(18, 2) DEFAULT 0,
    AVG_RISK_SCORE NUMBER(5, 4) DEFAULT 0,
    REFRESHED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SUMMARY_DATE, CATEGORY_CODE)
);

-- Model Performance Tracking
CREATE TABLE IF NOT EXISTS REPORTING.MODEL_PERFORMANCE_DAILY (
    SUMMARY_DATE DATE NOT NULL,
    MODEL_NAME VARCHAR(100) NOT NULL,
    MODEL_VERSION VARCHAR(20) NOT NULL,
    PREDICTIONS_COUNT NUMBER DEFAULT 0,
    AVG_SCORE NUMBER(5, 4) DEFAULT 0,
    SCORE_STDDEV NUMBER(5, 4) DEFAULT 0,
    TRUE_POSITIVES NUMBER DEFAULT 0,
    FALSE_POSITIVES NUMBER DEFAULT 0,
    TRUE_NEGATIVES NUMBER DEFAULT 0,
    FALSE_NEGATIVES NUMBER DEFAULT 0,
    PRECISION_SCORE NUMBER(5, 4) DEFAULT 0,
    RECALL_SCORE NUMBER(5, 4) DEFAULT 0,
    F1_SCORE NUMBER(5, 4) DEFAULT 0,
    AUC_ROC NUMBER(5, 4) DEFAULT 0,
    AVG_LATENCY_MS NUMBER DEFAULT 0,
    P95_LATENCY_MS NUMBER DEFAULT 0,
    REFRESHED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SUMMARY_DATE, MODEL_NAME, MODEL_VERSION)
);

-- Alert Resolution Metrics
CREATE TABLE IF NOT EXISTS REPORTING.ALERT_RESOLUTION_METRICS (
    SUMMARY_DATE DATE NOT NULL,
    SEVERITY VARCHAR(20) NOT NULL,
    ALERTS_CREATED NUMBER DEFAULT 0,
    ALERTS_RESOLVED NUMBER DEFAULT 0,
    ALERTS_ESCALATED NUMBER DEFAULT 0,
    FALSE_POSITIVES NUMBER DEFAULT 0,
    AVG_RESOLUTION_TIME_MINUTES NUMBER DEFAULT 0,
    MEDIAN_RESOLUTION_TIME_MINUTES NUMBER DEFAULT 0,
    P95_RESOLUTION_TIME_MINUTES NUMBER DEFAULT 0,
    SLA_COMPLIANCE_RATE NUMBER(5, 4) DEFAULT 0,
    REFRESHED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SUMMARY_DATE, SEVERITY)
);

-- Executive KPI Summary (weekly rollup)
CREATE TABLE IF NOT EXISTS REPORTING.WEEKLY_EXECUTIVE_SUMMARY (
    WEEK_START_DATE DATE NOT NULL,
    WEEK_END_DATE DATE NOT NULL,
    TOTAL_TRANSACTIONS NUMBER DEFAULT 0,
    TOTAL_AMOUNT NUMBER(18, 2) DEFAULT 0,
    FRAUD_PREVENTED_COUNT NUMBER DEFAULT 0,
    FRAUD_PREVENTED_AMOUNT NUMBER(18, 2) DEFAULT 0,
    FRAUD_RATE_CHANGE_PCT NUMBER(7, 4) DEFAULT 0,
    MODEL_ACCURACY NUMBER(5, 4) DEFAULT 0,
    SYSTEM_UPTIME_PCT NUMBER(5, 2) DEFAULT 99.9,
    AVG_DETECTION_LATENCY_MS NUMBER DEFAULT 0,
    ALERTS_TOTAL NUMBER DEFAULT 0,
    ALERTS_RESOLVED NUMBER DEFAULT 0,
    FALSE_POSITIVE_RATE NUMBER(7, 4) DEFAULT 0,
    TOP_FRAUD_CATEGORY VARCHAR(100),
    TOP_FRAUD_COUNTRY VARCHAR(3),
    REFRESHED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (WEEK_START_DATE)
);
