-- =============================================================================
-- Snowflake STAGING Schema
-- Cleansed and typed data parsed from RAW VARIANT
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS STAGING;

CREATE TABLE IF NOT EXISTS STAGING.STG_TRANSACTIONS (
    TRANSACTION_ID VARCHAR(64) NOT NULL,
    EXTERNAL_TRANSACTION_ID VARCHAR(64) NOT NULL,
    ACCOUNT_ID VARCHAR(64) NOT NULL,
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    MERCHANT_ID VARCHAR(64),
    MERCHANT_NAME VARCHAR(255),
    MERCHANT_CATEGORY_CODE VARCHAR(10),
    TRANSACTION_AMOUNT NUMBER(15, 2) NOT NULL,
    TRANSACTION_CURRENCY VARCHAR(3) NOT NULL,
    TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    CHANNEL VARCHAR(20) NOT NULL,
    CARD_TYPE VARCHAR(20),
    CARD_LAST_FOUR VARCHAR(4),
    IP_ADDRESS VARCHAR(45),
    DEVICE_ID VARCHAR(128),
    DEVICE_TYPE VARCHAR(50),
    GEO_LATITUDE NUMBER(10, 8),
    GEO_LONGITUDE NUMBER(11, 8),
    GEO_COUNTRY VARCHAR(3),
    GEO_CITY VARCHAR(100),
    IS_INTERNATIONAL BOOLEAN DEFAULT FALSE,
    TRANSACTION_TIMESTAMP TIMESTAMPTZ NOT NULL,
    PROCESSED_TIMESTAMP TIMESTAMPTZ,
    STATUS VARCHAR(20),
    BATCH_ID VARCHAR(50) NOT NULL,
    LOADED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Clustering for common query patterns
ALTER TABLE STAGING.STG_TRANSACTIONS SET CLUSTER BY (TRANSACTION_TIMESTAMP, ACCOUNT_ID);

CREATE TABLE IF NOT EXISTS STAGING.STG_FRAUD_ALERTS (
    ALERT_ID VARCHAR(64) NOT NULL,
    TRANSACTION_ID VARCHAR(64) NOT NULL,
    ALERT_TYPE VARCHAR(50) NOT NULL,
    RULE_ID VARCHAR(50),
    RISK_SCORE NUMBER(5, 4),
    SEVERITY VARCHAR(20) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(2000),
    DETAILS VARIANT,
    ASSIGNED_TO VARCHAR(100),
    RESOLVED_AT TIMESTAMPTZ,
    RESOLUTION_NOTES VARCHAR(4000),
    CREATED_AT TIMESTAMPTZ NOT NULL,
    BATCH_ID VARCHAR(50) NOT NULL,
    LOADED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS STAGING.STG_RISK_SCORES (
    SCORE_ID VARCHAR(64) NOT NULL,
    TRANSACTION_ID VARCHAR(64) NOT NULL,
    MODEL_VERSION VARCHAR(20) NOT NULL,
    OVERALL_SCORE NUMBER(5, 4) NOT NULL,
    RULE_SCORE NUMBER(5, 4),
    ANOMALY_SCORE NUMBER(5, 4),
    ML_SCORE NUMBER(5, 4),
    FEATURE_CONTRIBUTIONS VARIANT,
    SCORING_TIMESTAMP TIMESTAMPTZ NOT NULL,
    LATENCY_MS NUMBER,
    BATCH_ID VARCHAR(50) NOT NULL,
    LOADED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS STAGING.STG_CUSTOMER_PROFILES (
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    TOTAL_TRANSACTIONS_24H NUMBER DEFAULT 0,
    TOTAL_AMOUNT_24H NUMBER(15, 2) DEFAULT 0,
    TOTAL_TRANSACTIONS_7D NUMBER DEFAULT 0,
    TOTAL_AMOUNT_7D NUMBER(15, 2) DEFAULT 0,
    AVG_TRANSACTION_AMOUNT NUMBER(15, 2),
    MAX_TRANSACTION_AMOUNT NUMBER(15, 2),
    UNIQUE_MERCHANTS_7D NUMBER DEFAULT 0,
    UNIQUE_COUNTRIES_7D NUMBER DEFAULT 0,
    LAST_TRANSACTION_TIMESTAMP TIMESTAMPTZ,
    RISK_TIER VARCHAR(20),
    BATCH_ID VARCHAR(50) NOT NULL,
    LOADED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP()
);
