-- =============================================================================
-- Migration 002: Create Fraud Alerts Table
-- RiskPulse Fraud Analytics Platform
-- =============================================================================

BEGIN;

CREATE TABLE fraud_alerts (
    alert_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_id UUID NOT NULL REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    alert_type VARCHAR(50) NOT NULL CHECK (alert_type IN ('rule_based', 'anomaly', 'ml_score', 'ensemble')),
    rule_id VARCHAR(50),
    risk_score DECIMAL(5, 4) CHECK (risk_score BETWEEN 0 AND 1),
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'investigating', 'resolved', 'false_positive')),
    description TEXT,
    details JSONB DEFAULT '{}',
    assigned_to VARCHAR(100),
    resolved_at TIMESTAMPTZ,
    resolution_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Performance indexes
CREATE INDEX idx_fraud_alerts_transaction ON fraud_alerts(transaction_id);
CREATE INDEX idx_fraud_alerts_severity ON fraud_alerts(severity);
CREATE INDEX idx_fraud_alerts_status ON fraud_alerts(status);
CREATE INDEX idx_fraud_alerts_created ON fraud_alerts(created_at DESC);
CREATE INDEX idx_fraud_alerts_assigned ON fraud_alerts(assigned_to) WHERE assigned_to IS NOT NULL;

-- Composite index for investigation console queries
CREATE INDEX idx_fraud_alerts_status_severity ON fraud_alerts(status, severity, created_at DESC);

-- GIN index for JSONB details queries
CREATE INDEX idx_fraud_alerts_details ON fraud_alerts USING GIN (details);

CREATE TRIGGER trg_fraud_alerts_updated_at
    BEFORE UPDATE ON fraud_alerts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE fraud_alerts IS 'Fraud alerts generated by detection engine';
COMMENT ON COLUMN fraud_alerts.risk_score IS 'Composite risk probability (0.0000 to 1.0000)';
COMMENT ON COLUMN fraud_alerts.details IS 'Structured context: triggered rules, feature values, scoring breakdown';

COMMIT;
