"""Storage module - PostgreSQL, Snowflake, S3, Redis, and unified orchestrator."""

from src.storage.cache_handler import (
    CacheConnectionError,
    CacheHandler,
    CacheHandlerError,
    CacheMetrics,
    CacheOperationError,
    CacheStrategy,
    create_cache_handler,
)
from src.storage.local_object_storage import (
    LocalObjectNotFoundError,
    LocalObjectStorageClient,
    LocalObjectStorageError,
    LocalObjectStorageHandler,
)
from src.storage.local_warehouse_handler import LocalWarehouseHandler
from src.storage.models import (
    AuditLog,
    Base,
    CustomerProfile,
    FraudAlert,
    RiskScore,
    Transaction,
)
from src.storage.postgres_handler import (
    BulkOperationError,
    ConnectionError,
    PoolStats,
    PostgresHandler,
    PostgresHandlerError,
    QueryError,
    QueryMetrics,
    create_postgres_handler,
)
from src.storage.s3_handler import (
    S3_BUCKET_ARCHIVE,
    S3_BUCKET_MODELS,
    S3_BUCKET_PROCESSED,
    S3_BUCKET_RAW,
    S3ConfigError,
    S3DownloadError,
    S3Handler,
    S3HandlerError,
    S3Metrics,
    S3UploadError,
    StorageLayer,
    get_s3_handler,
)
from src.storage.snowflake_handler import (
    SCHEMA_ANALYTICS,
    SCHEMA_RAW,
    SCHEMA_REPORTING,
    SCHEMA_STAGING,
    FileFormat,
    LoadMetrics,
    LoadStrategy,
    QueryResult,
    SnowflakeConnectionError,
    SnowflakeHandler,
    SnowflakeHandlerError,
    SnowflakeLoadError,
    SnowflakeMetrics,
    SnowflakeQueryError,
    SnowflakeSchemaError,
    WatermarkState,
    create_snowflake_handler,
)
from src.storage.storage_orchestrator import (
    BackendHealth,
    OrchestratedWriteResult,
    StorageBackend,
    StorageOrchestrator,
    StorageState,
    WriteResult,
    create_storage_orchestrator,
)

__all__ = [
    # PostgreSQL
    "PostgresHandler",
    "PostgresHandlerError",
    "ConnectionError",
    "QueryError",
    "BulkOperationError",
    "PoolStats",
    "QueryMetrics",
    "create_postgres_handler",
    # ORM Models
    "Base",
    "Transaction",
    "FraudAlert",
    "RiskScore",
    "CustomerProfile",
    "AuditLog",
    # S3
    "S3Handler",
    "S3HandlerError",
    "S3UploadError",
    "S3DownloadError",
    "S3ConfigError",
    "S3Metrics",
    "StorageLayer",
    "get_s3_handler",
    "S3_BUCKET_RAW",
    "S3_BUCKET_PROCESSED",
    "S3_BUCKET_MODELS",
    "S3_BUCKET_ARCHIVE",
    "LocalObjectStorageHandler",
    "LocalObjectStorageClient",
    "LocalObjectStorageError",
    "LocalObjectNotFoundError",
    "LocalWarehouseHandler",
    # Snowflake
    "SnowflakeHandler",
    "SnowflakeHandlerError",
    "SnowflakeConnectionError",
    "SnowflakeQueryError",
    "SnowflakeLoadError",
    "SnowflakeSchemaError",
    "SnowflakeMetrics",
    "LoadMetrics",
    "LoadStrategy",
    "FileFormat",
    "QueryResult",
    "WatermarkState",
    "create_snowflake_handler",
    "SCHEMA_RAW",
    "SCHEMA_STAGING",
    "SCHEMA_ANALYTICS",
    "SCHEMA_REPORTING",
    # Redis Cache
    "CacheHandler",
    "CacheHandlerError",
    "CacheConnectionError",
    "CacheOperationError",
    "CacheMetrics",
    "CacheStrategy",
    "create_cache_handler",
    # Storage Orchestrator
    "StorageOrchestrator",
    "StorageBackend",
    "StorageState",
    "BackendHealth",
    "WriteResult",
    "OrchestratedWriteResult",
    "create_storage_orchestrator",
]
