"""Storage module - PostgreSQL, Snowflake, S3, and Redis handlers."""

from src.storage.models import (
    AuditLog,
    Base,
    CustomerProfile,
    FraudAlert,
    RiskScore,
    Transaction,
)
from src.storage.postgres_handler import (
    BulkOperationError,
    ConnectionError,
    PostgresHandler,
    PostgresHandlerError,
    PoolStats,
    QueryError,
    QueryMetrics,
    create_postgres_handler,
)
from src.storage.s3_handler import (
    S3Handler,
    S3HandlerError,
    S3UploadError,
    S3DownloadError,
    S3ConfigError,
    S3Metrics,
    StorageLayer,
    get_s3_handler,
    S3_BUCKET_RAW,
    S3_BUCKET_PROCESSED,
    S3_BUCKET_MODELS,
    S3_BUCKET_ARCHIVE,
)
from src.storage.snowflake_handler import (
    SnowflakeHandler,
    SnowflakeHandlerError,
    SnowflakeConnectionError,
    SnowflakeQueryError,
    SnowflakeLoadError,
    SnowflakeSchemaError,
    SnowflakeMetrics,
    LoadMetrics,
    LoadStrategy,
    FileFormat,
    QueryResult,
    WatermarkState,
    create_snowflake_handler,
    SCHEMA_RAW,
    SCHEMA_STAGING,
    SCHEMA_ANALYTICS,
    SCHEMA_REPORTING,
)

__all__ = [
    # PostgreSQL
    "PostgresHandler",
    "PostgresHandlerError",
    "ConnectionError",
    "QueryError",
    "BulkOperationError",
    "PoolStats",
    "QueryMetrics",
    "create_postgres_handler",
    # ORM Models
    "Base",
    "Transaction",
    "FraudAlert",
    "RiskScore",
    "CustomerProfile",
    "AuditLog",
    # S3
    "S3Handler",
    "S3HandlerError",
    "S3UploadError",
    "S3DownloadError",
    "S3ConfigError",
    "S3Metrics",
    "StorageLayer",
    "get_s3_handler",
    "S3_BUCKET_RAW",
    "S3_BUCKET_PROCESSED",
    "S3_BUCKET_MODELS",
    "S3_BUCKET_ARCHIVE",
    # Snowflake
    "SnowflakeHandler",
    "SnowflakeHandlerError",
    "SnowflakeConnectionError",
    "SnowflakeQueryError",
    "SnowflakeLoadError",
    "SnowflakeSchemaError",
    "SnowflakeMetrics",
    "LoadMetrics",
    "LoadStrategy",
    "FileFormat",
    "QueryResult",
    "WatermarkState",
    "create_snowflake_handler",
    "SCHEMA_RAW",
    "SCHEMA_STAGING",
    "SCHEMA_ANALYTICS",
    "SCHEMA_REPORTING",
]
